# Generated by Django 5.0 on 2025-11-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.jobseeker')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='job_applica_job_id_e29281_idx'), models.Index(fields=['job_seeker', 'status'], name='job_applica_job_see_07981d_idx')],
                'unique_together': {('job', 'job_seeker')},
            },
        ),
    ]
